-- Plugins
reload 'slik.plugins'

reload 'slik.functions'
reload 'slik.keys'
reload 'slik.builtin'
reload 'slik.opt'
reload 'slik.rust'
reload 'slik.go'
reload 'slik.lsp'
reload 'slik.customvim'
reload 'slik.dap'
reload 'slik.dap2'
reload 'slik.navbuddy'
reload 'slik.theme'

-- Plugins
reload 'slik.wilder'
reload 'slik.material'
reload 'slik.aerial'
reload 'slik.luasnip'
reload 'slik.fidget'
reload 'slik.tokyonight'
reload 'slik.chatgpt'
reload 'slik.copilot'
reload 'slik.nim'
reload 'slik.oil'
reload 'slik.easyread'
