"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """
[╭{slik} ](fg:#00F8BE bold)$username$directory$battery$all$line_break$character"""

right_format = """$git_branch$git_state$git_status$time$cmd_duration"""

[character]
success_symbol = '[╰─➣](fg:#00F8BE bold)'
error_symbol = '[╰─➣](fg:#CC2B52 bold)'
vimcmd_symbol = '[╰─🚀](fg:#00F8BE bold)'


[git_branch]
format = '[ $symbol$branch]($style) '
style = 'cyan'

[directory]
format = "[](fg:#00F8BE bg:none)[$path]($style)[ ](fg:#00F8BE bg:none)"
style = "fg:#000000 bg:#00F8BE"
truncate_to_repo=false

[username]
show_always = true

[time]
disabled = false

[cmd_duration]
min_time = 0
disabled = false

[battery]
disabled = false
