"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """

[╭](fg:#5E5E5E bold bg:none)[$username$directory$battery$all$line_break$character](bg:none bold fg:#00F8BE)"""

right_format = """$git_branch$git_state$git_status$time$cmd_duration"""

[character]
success_symbol = '[╰─🤙](bg:none bold fg:#5E5E5E)'
error_symbol = '[╰─🫸](bg:none bold fg:#5E5E5E)'
vimcmd_symbol = '[╰─🤌](bg:none bold fg:#5E5E5E)'


[git_branch]
format = '[ $symbol$branch]($style) '
style = 'cyan'

[directory]
format = "[](bg:none fg:#5E5E5E)[$path]($style)[ ](bg:none fg:#5E5E5E)"
style = "fg:#00F8BE bg:#5E5E5E bold"
truncate_to_repo=false

[username]
show_always = false

[time]
disabled = false

[cmd_duration]
min_time = 0
disabled = false

[battery]
disabled = false
