function loi --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LO_OPTIONS' --description 'alias loi exa $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LO_OPTIONS'
    eza $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LO_OPTIONS $argv

end
